### ISSUE TITLE
pip install git+https://github.com/strath-sdr/rfsoc_studio@v0.2.1

### ISSUE THREAD

**Issue by mayukh4** [strath-sdr/rfsoc_studio#10]
ERROR: Command errored out with exit status 128: git clone -q https://github.com/strath-sdr/rfsoc_studio /tmp/pip-req-build-4u3xigct Check the logs for full command output.

I get this error message when I try to install the rfsoc studio via the terminal. Please help as I am not being able to install the extra packages.

**Comment by dnorthcote** [comment]
Hi mayukh4,


Happy to help and get you up and running with the RFSoC studio. I have a few questions that will help me debug your issue further, and resolve any problems in the future.

Can I ask the following:
* What RFSoC development board are you using?
* What version of PYNQ are you using?
* When you attempted to install the RFSoC studio, did you use a fresh install of PYNQ?
* Did you attempt to install the RFSoC studio via a UART terminal, or did you install it using the Jupyter Lab terminal?
* Is your development board connected to the internet?
* I notice that the name of this issue is the command to install the RFSoC Studio. However, you use `pip` rather than `pip3`. Is `pip` the command you used when installing RFSoC Studio or did you use `pip3`?


Kind regards,
David.
